spring:
  datasource:
    username: ivan
    url: jdbc:postgresql://localhost:5432/Library
    password: '123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
